# Generated by Django 4.1.7 on 2023-03-11 23:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Driver', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vihicle',
            name='car_registration',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='Driver.drivers'),
            preserve_default=False,
        ),
    ]
